language: julia
julia:
    - nightly
    - 1.0.5
    - 1.3.1
    - 1.4.0
    - 1.4.1

codecov: true
coveralls: true

after_success:
  - julia -e 'cd(Pkg.dir("Dispersions")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
